### PR TITLE
chore(devDeps): bump undici to 5.10.0

### PR DESCRIPTION
**Pull request by SukkaW**
When @Zxilly is playing around with Next.js API Route with Experimental Edge Runtime, he tries to get a body from an empty response (where its statusCode could be 204, 205, or 304, etc.). He gets an empty TypeError with it.

When I am tracking down the issue through Next.js' source code, I notice that the only way Next.js could throw an empty TypeError is through the pre-compiled version of Edge Runtime. Further digging leads me to the `nodejs/undici`. Then I find out that `undici` has already fixed the issue (https://github.com/nodejs/undici/pull/1508). With that PR merged, `undici` now throws fetch spec compliant error instead of an empty TypeError.

This change is landed in `undici@5.6.0`, `edge-runtime` is still using `undici@5.5.0`, thus the empty TypeError is still occurring in Next.js Edge API Route.

The PR fixes the issue by bumping the version of `undici` to the latest version `5.9.1`.

### CODE REVIEW

**Comment by SukkaW** [comment]
`undici` seems to remove `undici/lib/core/headers`. I will mark this PR as WIP first.

**Comment by SukkaW** [comment]
**undici** has released `5.10.0`. The PR is ready for review now.

**Comment by SukkaW** [comment]
The reason CI tests failed is here: https://github.com/nodejs/undici/blob/6a87bfb38b3f4a28be81d2cc44a80083a0e4f798/lib/fetch/request.js#L839

`undici` require `AbortSignal` to exist even its webidl check just simply ignore it.

**Review by Kikobeats — APPROVED** [review]

**Comment by Kikobeats** [comment]
@SukkaW Thanks for this, released at v.1.0-beta.34 🙂

**Pull request merged**
