### PR TITLE
Update stream.ts to fix error on update Undici

### PR DESCRIPTION
**Pull request by martinez-hugo**

### CODE REVIEW

**Comment by martinez-hugo** [comment]
Link to https://github.com/vercel/vercel/pull/10767 & https://github.com/vercel/vercel/pull/10761

**Comment by Kikobeats** [comment]
@martinez-hugo thanks for this! Can you explain a bit what's the issue? 

Adding a test case can also clarifying what's happening here 🙂

**Comment by martinez-hugo** [comment]
This issue is linked to the upgrading of undici package and the replaces of `undici.fetch` by `undici.request`.
When we do that, like in `@vercel/node-utils` pkg, we have a type error as it : 

```
error TS2345: Argument of type 'Readable' is not assignable to parameter of type 'ReadableStream<any>'.
    Type 'Readable' is missing the following properties from type 'ReadableStream<any>': locked, cancel, getReader, pipeThrough, and 2 more.
```

And this error refer to our invocation of toToReadable function with a type of our first argument as Readable and not ReadableStream

**Comment by Kikobeats** [comment]
The `toToReadable` is expecting a web stream with `getReader` method:
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader

Tests are failing since `Readable` is extending from `NodeJS.ReadableStream` which it isn't a web stream

**Pull request closed without merging**
